// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1zIGfwcBM1XoIJFiKtF4CcaXOI3et4Uo',
    appId: '1:1087866779795:web:ecd67672e731e60305b566',
    messagingSenderId: '1087866779795',
    projectId: 'telematics-sample-cd2af',
    authDomain: 'telematics-sample-cd2af.firebaseapp.com',
    databaseURL: 'https://telematics-sample-cd2af-default-rtdb.firebaseio.com',
    storageBucket: 'telematics-sample-cd2af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk9910ZhjWPYEzRZbfqiy7brmhVjN0_QU',
    appId: '1:1087866779795:android:8f81bce241d4c66a05b566',
    messagingSenderId: '1087866779795',
    projectId: 'telematics-sample-cd2af',
    databaseURL: 'https://telematics-sample-cd2af-default-rtdb.firebaseio.com',
    storageBucket: 'telematics-sample-cd2af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNEAhsAKa8AnPKyiJ6UYysCNwzFPeBOfQ',
    appId: '1:1087866779795:ios:1a4a02bc0eb5444105b566',
    messagingSenderId: '1087866779795',
    projectId: 'telematics-sample-cd2af',
    databaseURL: 'https://telematics-sample-cd2af-default-rtdb.firebaseio.com',
    storageBucket: 'telematics-sample-cd2af.appspot.com',
    iosBundleId: 'com.example.sdkDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNEAhsAKa8AnPKyiJ6UYysCNwzFPeBOfQ',
    appId: '1:1087866779795:ios:5146923f363f162505b566',
    messagingSenderId: '1087866779795',
    projectId: 'telematics-sample-cd2af',
    databaseURL: 'https://telematics-sample-cd2af-default-rtdb.firebaseio.com',
    storageBucket: 'telematics-sample-cd2af.appspot.com',
    iosBundleId: 'com.example.sdkDemo.RunnerTests',
  );
}
